//NOTIFICATION
export const NOTIFICATION_SEND = 'NOTIFICATION_SEND';
export const NOTIFICATION_CLOSE = 'NOTIFICATION_CLOSE';
export const NOTIFICATION_CLOSE_ALL = 'NOTIFICATION_CLOSE_ALL';

//AUTHENTICATION
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

//PROFILE
export const PROFILE_FETCH_DATA_START = 'PROFILE_FETCH_DATA_START';
export const PROFILE_FETCH_DATA_SUCCESS = 'PROFILE_FETCH_DATA_SUCCESS';
export const PROFILE_FETCH_DATA_FAIL = 'PROFILE_FETCH_DATA_FAIL';
export const PROFILE_CLEAR_DATA = 'PROFILE_CLEAR_DATA';
export const PROFILE_EDIT_START = 'PROFILE_EDIT_START';
export const PROFILE_EDIT_SUCCESS = 'PROFILE_EDT_SUCCESS';
export const PROFILE_EDIT_FAILED = 'PROFILE_EDIT_FAILED';
export const PROFILE_DELETE_START = 'PROFILE_DELETE_START';
export const PROFILE_DELETE_SUCCESS = 'PROFILE_DELETE_SUCCESS';
export const PROFILE_DELETE_FAILED = 'PROFILE_DELTE_FALIED';
export const PROFILE_PUT_BOOKMARK_START = 'PROFILE_PUT_BOOKMARK_START';
export const PROFILE_PUT_BOOKMARK_SUCCESS = 'PROFILE_PUT_BOOKMARK_SUCCESS';
export const PROFILE_PUT_BOOKMARK_FAIL = 'PROFILE_PUT_BOOKMARK_FAIL';

//VIDEO
export const VIDEO_UPLOAD_START = 'VIDEO_UPLOAD_START';
export const VIDEO_UPLOAD_SUCCESS = 'VIDEO_UPLOAD_SUCCESS';
export const VIDEO_UPLOAD_FAILED = 'VIDEO_UPLOAD_FAILED';
export const VIDEO_STREAM_START = 'VIDEO_STREAM_START';
export const VIDEO_STREAM_SUCESS = 'VIDEO_STREAM_SUCCESS';
export const VIDEO_STREAM_FAILED = 'VIDEO_STREAM_FAILED';
export const VIDEO_FETCH_INFO_START = 'VIDEO_FETCH_INFO_START';
export const VIDEO_FETCH_INFO_SUCCESS = 'VIDEO_FETCH_INFO_SUCCESS';
export const VIDEO_FETCH_INFO_FAILED = 'VIDEO_FETCH_INFO_FAILED';
export const VIDEO_FETCH_COMMENTS_START = 'VIDEO_FETCH_COMMENTS_START';
export const VIDEO_FETCH_COMMENTS_SUCCESS = 'VIDEO_FETCH_COMMENTS_SUCCESS';
export const VIDEO_FETCH_COMMENTS_FAILED = 'VIDEO_FETCH_COMMENTS_FAILED';
export const VIDEO_UPLOAD_COMMENT_START = 'VIDEO_UPLOAD_COMMENT_START';
export const VIDEO_UPLOAD_COMMENT_SUCCESS = 'VIDEO_UPLOAD_COMMENT_SUCCESS';
export const VIDEO_UPLOAD_COMMENT_FAILED = 'VIDEO_UPLOAD_COMMENT_FAILED';
export const VIDEO_RATE_START = 'VIDEO_RATE_START';
export const VIDEO_RATE_SUCCESS = 'VIDEO_RATE_SUCCESS';
export const VIDEO_RATE_FAILED = 'VIDEO_RATE_FAILED';
export const VIDEO_ADD_VIEW_START = 'VIDEO_ADD_VIEW_START';
export const VIDEO_ADD_VIEW_SUCCESS = 'VIDEO_ADD_VIEW';
export const VIDEO_ADD_VIEW_FAILED = 'VIDEO_ADD_VIEW_FAILED';
export const VIDEO_EDIT_START = 'VIDEO_EDIT_START';
export const VIDEO_EDIT_SUCCESS = 'VIDEO_EDIT_SUCCESS';
export const VIDEO_EDIT_FAILED = 'VIDEO_EDIT_FAILED';
export const VIDEO_DELETE_START = 'VIDEO_DELETE_START';
export const VIDEO_DELETE_SUCCESS = 'VIDEO_DELETE_SUCCESS';
export const VIDEO_DELETE_FAILED = 'VIDEO_DELTE_FALIED';

//PLAYLIST
export const PLAYLIST_ON = 'PLAYLIST_ON';
export const PLAYLIST_OFF = 'PLAYLIST_OFF';
export const PLAYLIST_FETCH_DATA_START = 'PLAYLIST_FETCH_DATA_START';
export const PLAYLIST_FETCH_DATA_SUCCESS = 'PLAYLIST_FETCH_DATA_SUCCESS';
export const PLAYLIST_FETCH_DATA_FAILED = 'PLAYLIST_FETCH_DATA_FAILED';
export const PLAYLIST_FETCH_VIDEO_INFO_START = 'PLAYLIST_FETCH_VIDEO_INFO_START';
export const PLAYLIST_FETCH_VIDEO_INFO_FAILED = 'PLAYLIST_FETCH_VIDEO_INFO_FAILED';
export const PLAYLIST_FETCH_VIDEO_INFO_SUCCESS = 'PLAYLIST_FETCH_VIDEO_INFO_SUCCESS';
export const PLAYLIST_UPLOAD_START = 'PLAYLIST_UPLOAD_START';
export const PLAYLIST_UPLOAD_SUCCESS = 'PLAYLIST_UPLOAD_SUCCESS';
export const PLAYLIST_UPLOAD_FAILED = 'PLAYLIST_UPLOAD_FAILED';
export const PLAYLIST_EDIT_START = 'PLAYLIST_EDIT_START';
export const PLAYLIST_EDIT_SUCCESS = 'PLAYLIST_EDIT_SUCCESS';
export const PLAYLIST_EDIT_FAILED = 'PLAYLIST_EDIT_FAILED';
export const PLAYLIST_DELETE_START = 'PLAYLIST_DELETE_START';
export const PLAYLIST_DELETE_SUCCESS = 'PLAYLIST_DELETE_SUCCESS';
export const PLAYLIST_DELETE_FAILED = 'PLAYLIST_DELTE_FALIED';
export const PLAYLIST_SET_CURRENT_VIDEO = 'PLAYLIST_SET_CURRENT_VIDEO';

//CATEGORY
export const CATEGORY_UPLOAD_START = 'CATEGORY_UPLOAD_START';
export const CATEGORY_UPLOAD_SUCCESS = 'CATEGORY_UPLOAD_SUCCESS';
export const CATEGORY_UPLOAD_FAILED = 'CATEGORY_UPLOAD_FAILED';
export const CATEGORY_FETCH_START = 'CATEGORY_FETCH_START';
export const CATEGORY_FETCH_SUCCESS = 'CATEGORY_FETCH_SUCCESS';
export const CATEGORY_FETCH_FAILED = 'CATEGORY_FETCH_FAILED';
export const CATEGORY_EDIT_START = 'CATEGORY_EDIT_START';
export const CATEGORY_EDIT_SUCCESS = 'CATEGORY_EDIT_SUCCESS';
export const CATEGORY_EDIT_FAILED = 'CATEGORY_EDIT_FAILED';
export const CATEGORY_DELETE_START = 'CATEGORY_DELETE_START';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_DELETE_FAILED = 'CATEGORY_DELETE_FAILED';

//ADMIN
export const ADMIN_FETCH_PROFILES_START = 'ADMIN_FETCH_PROFILES_START';
export const ADMIN_FETCH_PROFILES_SUCCESS = 'ADMIN_FETCH_PROFILES_SUCCESS';
export const ADMIN_FETCH_PROFILES_FAILED = 'ADMIN_FETCH_PROFILES_FAILED';
export const ADMIN_FETCH_VIDEOS_START = 'ADMIN_FETCH_VIDEOS_START';
export const ADMIN_FETCH_VIDEOS_SUCCESS = 'ADMIN_FETCH_VIDEOS_SUCCESS';
export const ADMIN_FETCH_VIDEOS_FAILED = 'ADMIN_FETCH_VIDEOS_FAILED';
