//AUTHENTICATION
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CLEAR_NOTIFICATION = 'AUTH_CLEAR_NOTIFICATION';
export const AUTH_CLEAR_NOTIFICATIONS = 'AUTH_CLEAR_NOTIFICATIONS';

//PROFILE
export const PROFILE_EDIT_START = 'PROFILE_EDIT_START';
export const PROFILE_EDIT_SUCCESS = 'PROFILE_SETTINGS_CHANGED';
export const PROFILE_EDIT_FAILED = 'PROFILE_EDIT_FAILED';
export const PROFILE_FETCH_DATA_START = 'PROFILE_FETCH_DATA_START';
export const PROFILE_FETCH_DATA = 'PROFILE_FETCH_DATA';
export const PROFILE_FETCH_DATA_SUCCESS = 'PROFILE_FETCH_DATA_SUCCESS';
export const PROFILE_FETCH_DATA_FAIL = 'PROFILE_FETCH_DATA_FAIL';
export const PROFILE_CLEAR_DATA = 'PROFILE_CLEAR_DATA';
export const PROFILE_CLEAR_NOTIFICATION = 'PROFILE_CLEAR_NOTIFICATION';
export const PROFILE_CLEAR_NOTIFICATIONS = 'PROFILE_CLEAR_NOTIFICATIONS';

//VIDEO
export const VIDEO_UPLOAD_START = 'VIDEO_UPLOAD_START';
export const VIDEO_UPLOAD = 'VIDEO_UPLOAD';
export const VIDEO_UPLOAD_SUCCESS = 'VIDEO_UPLOAD_SUCCESS';
export const VIDEO_UPLOAD_FAILED = 'VIDEO_UPLOAD_FAILED';
export const VIDEO_STREAM_START = 'VIDEO_STREAM_START';
export const VIDEO_STREAM_SUCESS = 'VIDEO_STREAM_SUCCESS';
export const VIDEO_STREAM_INTERRUPT = 'VIDEO_STREAM_INTERRUPT';
export const VIDEO_STREAM_FAILED = 'VIDEO_STREAM_FAILED';
export const VIDEO_FETCH_INFO_START = 'VIDEO_FETCH_INFO_START';
export const VIDEO_FETCH_INFO = 'VIDEO_FETCH_INFO';
export const VIDEO_FETCH_INFO_SUCCESS = 'VIDEO_FETCH_INFO_SUCCESS';
export const VIDEO_FETCH_INFO_FAILED = 'VIDEO_FETCH_INFO_FAILED';
export const VIDEO_FETCH_COMMENTS = 'VIDEO_FETCH_COMMENTS';
export const VIDEO_FETCH_COMMENTS_SUCCESS = 'VIDEO_FETCH_COMMENTS_SUCCESS';
export const VIDEO_FETCH_COMMENTS_FAILED = 'VIDEO_FETCH_COMMENTS_FAILED';
export const VIDEO_UPLOAD_COMMENTS = 'VIDEO_UPLOAD_COMMENTS';
export const VIDEO_UPLOAD_COMMENTS_SUCCESS = 'VIDEO_UPLOAD_COMMENTS_SUCCESS';
export const VIDEO_UPLOAD_COMMENTS_FAILED = 'VIDEO_UPLOAD_COMMENTS_FAILED';
export const VIDEO_RATE = 'VIDEO_RATE';
export const VIDEO_RATE_START = 'VIDEO_RATE_START';
export const VIDEO_RATE_SUCCESS = 'VIDEO_RATE_SUCCESS';
export const VIDEO_RATE_FAILED = 'VIDEO_RATE_FAILED';
export const VIDEO_CLEAR_NOTIFICATIONS = 'VIDEO_CLEAR_NOTIFICATIONS';
export const VIDEO_CLEAR_NOTIFICATION = 'VIDEO_CLEAR_NOTIFICATION';

//PLAYLIST
export const PLAYLIST_SHOW_FORM = 'PLAYLIST_SHOW_FORM';
export const PLAYLIST_CLOSE_FORM = 'PLAYLIST_CLOSE_FORM';
export const PLAYLIST_FETCH_DATA = 'PLAYLIST_FETCH_DATA';
export const PLAYLIST_FETCH_DATA_START = 'PLAYLIST_FETCH_DATA_START';
export const PLAYLIST_FETCH_DATA_SUCCESS = 'PLAYLIST_FETCH_DATA_SUCCESS';
export const PLAYLIST_FETCH_DATA_FAILED = 'PLAYLIST_FETCH_DATA_FAILED';
export const PLAYLIST_UPLOAD = 'PLAYLIST_UPLOAD';
export const PLAYLIST_UPLOAD_START = 'PLAYLIST_UPLOAD_START';
export const PLAYLIST_UPLOAD_SUCCESS = 'PLAYLIST_UPLOAD_SUCCESS';
export const PLAYLIST_UPLOAD_FAILED = 'PLAYLIST_UPLOAD_FAILED';
export const PLAYLIST_EDIT = 'PLAYLIST_EDIT';
export const PLAYLIST_EDIT_START = 'PLAYLIST_EDIT_START';
export const PLAYLIST_EDIT_SUCCESS = 'PLAYLIST_EDIT_SUCCESS';
export const PLAYLIST_EDIT_FAILED = 'PLAYLIST_EDIT_FAILED';
export const PLAYLIST_CLEAR_NOTIFICATIONS = 'PLAYLIST_CLEAR_NOTIFICATIONS';
export const PLAYLIST_CLEAR_NOTIFICATION = 'PLAYLIST_CLEAR_NOTIFICATION';
