export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const PROFILE_EDIT_START = 'PROFILE_EDIT_START';
export const PROFILE_EDIT_SUCCESS = 'PROFILE_SETTINGS_CHANGED';
export const PROFILE_EDIT_FAILED = 'PROFILE_EDIT_FAILED';
export const PROFILE_FETCH_DATA_START = 'PROFILE_FETCH_DATA_START';
export const PROFILE_FETCH_DATA_SUCCESS = 'PROFILE_FETCH_DATA_SUCCESS';
export const PROFILE_FETCH_DATA_FAIL = 'PROFILE_FETCH_DATA_FAIL';

export const VIDEO_UPLOAD_START = 'VIDEO_UPLOAD_START';
export const VIDEO_UPLOAD_SUCCESS = 'VIDEO_UPLOAD_SUCCESS';
export const VIDEO_UPLOAD_FAILED = 'VIDEO_UPLOAD_FAILED';
export const VIDEO_STREAM_START = 'VIDEO_STREAM_START';
export const VIDEO_STREAM_SUCESS = 'VIDEO_STREAM_SUCCESS';
export const VIDEO_STREAM_INTERRUPT = 'VIDEO_STREAM_INTERRUPT';
export const VIDEO_STREAM_FAILED = 'VIDEO_STREAM_FAILED';
export const VIDEO_FETCH_INFO_START = 'VIDEO_FETCH_INFO_START';
export const VIDEO_FETCH_INFO_SUCCESS = 'VIDEO_FETCH_INFO_SUCCESS';
export const VIDEO_FETCH_INFO_FAILED = 'VIDEO_FETCH_INFO_FAILED';